In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [49]:
df=pd.read_csv('/content/Iris.csv')
df=df.drop(['Id'],axis=1)
df['Species'] = df['Species'].map({'Iris-setosa':0 , 'Iris-versicolor':1 , 'Iris-virginica':2}).astype(int)
df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [50]:
df.shape

(150, 5)

In [51]:
df.isnull().sum()

,0
SepalLengthCm,0
SepalWidthCm,0
PetalLengthCm,0
PetalWidthCm,0
Species,0


In [52]:
training_data = df.iloc[ : 140 , :]
validation_data = df.iloc[140 : 148 , :]
testing_data = df.iloc[148 : ]

In [53]:
training_data.shape

(140, 5)

In [54]:
validation_data.shape

(8, 5)

In [55]:
testing_data.shape

(2, 5)

In [56]:
training_data_inde = training_data.iloc[: , :-1]
training_data_dep = training_data.iloc[: , -1]

In [57]:
validation_data_inde = validation_data.iloc[: , :-1]
validation_data_dep = validation_data.iloc[: , -1]

In [58]:
testing_data_inde = testing_data.iloc[: , :-1]
testing_data_dep = testing_data.iloc[: , -1]

In [59]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation
from tensorflow.keras.activations import relu,softmax

In [60]:
training_data_inde.shape[1]

4

In [61]:
import warnings
warnings.filterwarnings("ignore")

In [62]:
model = Sequential()

# input_layers to hiddel layer 1
model.add(Dense(units=10 ,
                kernel_initializer="he_uniform" ,
                activation="relu" ,
                input_dim = training_data_inde.shape[1])
)

# hiddel layer 1 to hidden layer 2
model.add(Dense(units=4 , kernel_initializer="he_uniform" ,activation="relu"))

# hiddel layer 2 to hidden layer 3
model.add(Dense(units=2 , kernel_initializer="he_uniform" ,activation="relu"))


# hiddel layer 3 to outputlayer
model.add(Dense(units= 3, kernel_initializer="glorot_uniform" ,activation="softmax")) ###### softmax

In [63]:
model.compile(optimizer="adam" , loss = "categorical_crossentropy" , metrics=["Accuracy"])

In [64]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113 (452.00 B)

 Trainable params: 113 (452.00 B)

 Non-trainable params: 0 (0.00 B)

In [65]:
from tensorflow.keras.utils import to_categorical

In [66]:
training_data_dep_converted = to_categorical(training_data_dep)

In [67]:
training_data_dep_converted

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [68]:
validation_data_dep_converted = to_categorical(validation_data_dep)

In [69]:
# Training _process

model.fit(training_data_inde ,
          training_data_dep_converted ,
          batch_size=10 ,
          epochs=50,
          validation_data = (validation_data_inde,validation_data_dep_converted)
          )

Epoch 1/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - Accuracy: 0.1214 - loss: 1.1234 - val_Accuracy: 0.0000e+00 - val_loss: 1.1002
Epoch 2/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - Accuracy: 0.3500 - loss: 1.0986 - val_Accuracy: 0.0000e+00 - val_loss: 1.1032
Epoch 3/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.3571 - loss: 1.0982 - val_Accuracy: 0.0000e+00 - val_loss: 1.1073
Epoch 4/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.3571 - loss: 1.0980 - val_Accuracy: 0.0000e+00 - val_loss: 1.1107
Epoch 5/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.3571 - loss: 1.0978 - val_Accuracy: 0.0000e+00 - val_loss: 1.1149
Epoch 6/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.3571 - loss: 1.0974 - val_Accuracy: 0.0000e+00 - val_loss: 1.1199
Epoch 7/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.3571 - loss: 1.0973 - val_Accuracy: 0.0000e+00 - val_loss: 1.1249
Epoch 8/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - Accuracy: 0.3571 - loss: 1.0970 - val

In [70]:
model.weights

[<Variable path=sequential_1/dense_4/kernel, shape=(4, 10), dtype=float32, value=[[ 0.52814364 -0.13985136  0.40754607 -0.22761501  0.968635    1.1573877
   -0.35142493 -0.7700369  -0.8492608   0.40183014]
  [ 0.3812454   0.79206175  0.23157729  0.88972265  0.73279995 -0.21116717
   -0.29745215 -0.06192338 -0.4747277  -0.19785167]
  [-0.27532262 -0.7832705  -0.21269697 -1.1511837   0.44951522 -0.22593367
   -0.7487569  -0.532674    0.14398587  0.74434686]
  [ 0.2316183   0.6476667  -0.22557391 -1.0736945   0.7202474  -0.9568949
    0.07350421  0.185359   -1.1958388  -0.21601826]]>,
 <Variable path=sequential_1/dense_4/bias, shape=(10,), dtype=float32, value=[-0.01792883 -0.01817981 -0.01829145  0.01325395  0.01848843 -0.01830886
   0.          0.          0.          0.01837499]>,
 <Variable path=sequential_1/dense_5/kernel, shape=(10, 4), dtype=float32, value=[[-0.04596865  0.09924082  0.6552024   0.5010273 ]
  [-0.7106068   0.20630728 -0.5475706   0.2817264 ]
  [-0.19999027  0.591365

In [71]:
testing_data_inde.shape

(2, 4)

In [72]:
testing_data_inde

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
148,6.2,3.4,5.4,2.3
149,5.9,3.0,5.1,1.8


In [73]:
results = model.predict(np.array([[6.2,3.4,5.4,2.3]]))
results

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step


array([[0.35214663, 0.35182953, 0.29602388]], dtype=float32)

In [74]:
2.0642657e-04 + 4.2153049e-01 + 5.7826310e-01

1.00000001657

In [75]:
labels = ['Setosa' , 'versicolor' , 'verginica']
print(labels[np.argmax(results)])

Setosa


In [76]:
results = model.predict(testing_data_inde)
results

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[0.35214663, 0.35182953, 0.29602388],
       [0.35214663, 0.35182953, 0.29602388]], dtype=float32)

In [77]:
for i in results:
  if np.argmax(i) == 0:
    print('setosa')
  elif np.argmax(i) == 1:
    print('versicolor')
  else:
    print('verginica')

setosa
setosa


In [78]:
c = []
for i in results:
  if np.argmax(i) == 0:
    c.append(0)
  elif np.argmax(i) == 1:
    c.append(1)
  else:
    c.append(2)

In [79]:
c

[0, 0]

In [80]:
testing_data_dep

,Species
148,2
149,2


In [81]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [82]:
confusion_matrix(testing_data_dep , c)

array([[0, 0],
       [2, 0]])

In [83]:
accuracy_score(testing_data_dep , c)

0.0

In [84]:
print(classification_report(testing_data_dep,c))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       2.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

